grader/urls.py
from django.conf.urls import url

from .views import submit_solution, check_solution, PreviousSubmission


app_name = 'grader'


urlpatterns = [
    url(r'^(?P<code>[A-Z]+)/submit/$', submit_solution, name='submit'),
    url(r'^(?P<code>[A-Z]+)/grade/(?P<pk>\d+)$', check_solution, name='grade'),
    url(r'^(?P<code>[A-Z]+)/submissions/$', PreviousSubmission.as_view(), name='previous_submissions'),
]

judge/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.views.generic import RedirectView

from .views import home, contact_page
from accounts.views import RegisterView, ProfileView, LoginView, LeaderBoardView


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^leaderboard/$', LeaderBoardView.as_view(), name='leaderboard'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^questions/', include('questions.urls', namespace='question')),
    url(r'^question/', include('grader.urls', namespace='grader')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.conf.urls import url

from .views import QuestionListView, QuestionDetailView


app_name = 'question'


urlpatterns = [
    url(r'^$', QuestionListView.as_view(), name='list'),
    url(r'^(?P<code>[A-Z]+)/$', QuestionDetailView.as_view(), name='detail'),
]

questions/models.py
import os

from django.db import models
from django.urls import reverse


def upload_question_image_location(instance, filename):
    file, ext = os.path.splitext(filename)
    location = 'questions/{code}{extension}'.format(code=instance.code, extension=ext)
    return location


class QuestionManager(models.Manager):

    def get_by_code(self, code):
        qs = self.get_queryset().filter(code=code)
        if qs.count() == 1:
            return qs.first()
        return None


class Question(models.Model):
    code = models.CharField(unique=True, max_length=10)
    title = models.CharField(unique=True, max_length=120)
    description = models.ImageField(upload_to=upload_question_image_location)
    time_limit = models.IntegerField(default=1)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = QuestionManager()

    def __str__(self):
        return self.code

    def get_absolute_url(self):
        return reverse('question:detail', kwargs={'code': self.code})

    def get_submit_url(self):
        return reverse('grader:submit', kwargs={'code': self.code})


def upload_test_case_file_location(instance, filename):
    location = 'test_cases/{code}/inputs/'.format(code=instance.question.code)
    return location + filename


class TestCaseQuerySet(models.query.QuerySet):

    def get_by_question(self, question_code):
        return self.filter(question__code=question_code)


class TestCaseManager(models.Manager):

    def get_queryset(self):
        return TestCaseQuerySet(self.model, using=self._db)

    def get_by_question(self, question_code):
        return self.get_queryset().get_by_question(question_code)


class TestCase(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    file = models.FileField(upload_to=upload_test_case_file_location)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = TestCaseManager()

    class Meta:
        ordering = ['file']

    def __str__(self):
        return self.question.code + ' - ' + self.file.name.split('/')[-1]

    @property
    def filename(self):
        """ Returns the name of the file without the preceding path """
        return self.file.name.split('/')[-1]


def upload_expected_output_file_location(instance, filename):
    location = 'test_cases/{code}/outputs/'.format(code=instance.question.code)
    return location + filename


class ExpectedOutputQuerySet(models.query.QuerySet):

    def get_by_question(self, question_code):
        return self.filter(question__code=question_code)

    def get_by_question_test_case(self, question_code, test_case):
        return self.get_by_question(question_code).filter(test_case=test_case)


class ExpectedOutputManager(models.Manager):

    def get_queryset(self):
        return ExpectedOutputQuerySet(self.model, using=self._db)

    def get_by_question(self, question_code):
        return self.get_queryset().get_by_question(question_code)

    def get_by_question_test_case(self, question_code, test_case):
        return self.get_queryset().get_by_question_test_case(question_code, test_case)


class ExpectedOutput(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE)
    file = models.FileField(upload_to=upload_expected_output_file_location)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ExpectedOutputManager()

    class Meta:
        ordering = ['file']

    def __str__(self):
        return self.question.code + ' - ' + self.file.name.split('/')[-1]

    @property
    def filename(self):
        """ Returns the name of the file without the preceding path """
        return self.file.name.split('/')[-1]

questions/views.py
import time
import pytz
from datetime import datetime
from datetime import date
from datetime import time
from datetime import timedelta

from django.utils.timezone import localtime, now
from django.views.generic import ListView, DetailView
from django.http import Http404
from django.db.models import Q, Max

from .models import Question
from judge.mixins import LoginRequiredMixin
from grader.models import Solution
from grader.utils import start_time

class QuestionListView(LoginRequiredMixin, ListView):
    template_name = 'questions/list.html'
    context_object_name='alert'


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(QuestionListView, self).get_context_data(**kwargs)

        if self.request.user and not self.request.user.is_admin:
            current_time = datetime.now()
            if current_time <= start_time:
                context['error'] = 'Contest has not started yet'
        return context

    def get_queryset(self):
        if self.request.user and not self.request.user.is_admin:
            current_time = datetime.now()
            if current_time <=start_time:
                self.template_name = 'home.html'

        questions = Question.objects.all()
        user = self.request.user
        for ques in questions:
            marks = Solution.objects.filter(Q(user=user) & Q(question=ques)).aggregate(Max('score'))
            if marks['score__max'] is None:
                ques.marks_obtained = 0
            else:
                ques.marks_obtained = marks['score__max']
        return questions


class QuestionDetailView(LoginRequiredMixin, DetailView):
    template_name = 'questions/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(QuestionDetailView, self).get_context_data(**kwargs)
        if self.request.user and not self.request.user.is_admin:
            current_time = datetime.now()
            future = start_time + timedelta(hours=1000000000)
            if current_time > future:
                context['error'] = 'Contest has ended.'
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        code = self.kwargs.get('code')
        instance = Question.objects.get_by_code(code)
        if instance is None:
            raise Http404('Question not found')
        return instance

questions/templates/questions/detail.html
{% extends 'base.html' %}

{% block base_head %}
<title>{{ object.code }}</title>
{% endblock %}

{% block content %}

<div class="jumbotron" style="padding-top: 10px;padding-left: 10px ;padding-bottom: 8px;margin-bottom:10px;margin-top:8px;padding-bottom: 15px">
    <div class="row">
        <div class="col-sm-2 " style="padding-top: 22px">
            <a href="{% url 'home'%}">
                <img src="https://image.ibb.co/cFLKpH/CODE_WARRIOR_N.png" alt="CODE_WARRIOR_N" border="0" style="width: 170px;height: 60px">
            </a>
        </div>
        <div id="head" class="col-sm-4 " style="padding-top: 28px">
            <strong><h1 id="Code">Code Warrior</h1></strong>
        </div>
        <div class="col-sm-6 ">
			<div id="clockdiv">
			    <div>
					<span id="days" class="days"></span>
					<div class="smalltext">days</div>
				</div>
				<div>
					<span id="hour" class="hours"></span>
					<div class="smalltext">Hours</div>
				</div>
				<div>
					<span id="minute" class="minutes"></span>
					<div class="smalltext">Minutes</div>
				</div>
				<div>
					<span id="second" class="seconds"></span>
					<div class="smalltext">Seconds</div>
				</div>
			</div>
			<script>
				// Set the date we're counting down to
				var countDownDate = new Date("May 9, 2019 9:59:59").getTime();

				// Update the count 	<h1>Countdown Clock</h1>down every 1 second
				var x = setInterval(function () {

					// Get todays date and time
					var now = new Date().getTime();

					// Find the distance between now an the count down date
					var distance = countDownDate - now;

					// Time calculations for days, hours, minutes and seconds
					var days = Math.floor(distance / (1000 * 60 * 60 * 24));
					var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
					var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
					var seconds = Math.floor((distance % (1000 * 60)) / 1000);

					// Output the result in an element with id="demo"
					document.getElementById("days").innerHTML = days;
					document.getElementById("hour").innerHTML = hours;
					document.getElementById("minute").innerHTML = minutes;
					document.getElementById("second").innerHTML = seconds;


					// If the count down is over, write some text
					if (distance < 0) {
						clearInterval(x);
						document.getElementById("days").innerHTML = "0";
						document.getElementById("hour").innerHTML = "0";
						document.getElementById("minute").innerHTML = "0";
						document.getElementById("second").innerHTML = "0";
					}
				}, 1000);
			</script>
		</div>
    </div>
</div>


<div class="jumbotron" style="padding-top: 15px;padding-left: 10px ;padding-bottom: 5px;margin-bottom:10px;margin-top:8px;">
    <div class="row">
        <div class="col-sm-4">
            {% if error %}
              <p style="color:red;">{{ error }}</p>
            {% else %}
            <a class="btn btn-success" href="{{ object.get_submit_url }}">Submit Solution</a>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <h3 style="color: rgb(59, 99, 99)" class="text-center">{{ object.code }}: {{ object.title }}</h3>
        </div>
        <div class="col-sm-4">
            <!--<a style="text-align: end" class="btn btn-primary" href="{% url 'grader:previous_submissions' object.code %}">Previous Submissions</a>-->
        </div>
    </div>
</div>

<div>
    <img src="{{ object.description.url }}" style="max-width:100%;height:auto;">
    <div class="jumbotron" style="padding-top: 10px;padding-left: 10px ;padding-bottom: 8px;margin-bottom:10px;margin-top:15px;padding-bottom: 20px ">
            {% if error %}
              <p style="color:red;">{{ error }}</p>
            {% else %}
            <a class="btn btn-success" href="{{ object.get_submit_url }}">Submit Solution</a>
            {% endif %}    </div>
    <div style="margin-bottom: 10px"></div>
</div>

{% endblock %}

questions/templates/questions/list.html
{% extends 'base.html' %}
<!-- {% load static %} -->
{% block base_head %}
<title>Questions</title>
{% endblock %} {% block content %}
<div class="jumbotron container" style="padding-top: 10px;padding-left: 10px ;padding-bottom: 8px;margin-bottom:10px;margin-top:8px;padding-bottom: 10px ">
		<div class="row">
		<div class="col-sm-2 " style="padding-top: 22px">
				<a href="{% url 'home'%}">
            <img src="https://image.ibb.co/cFLKpH/CODE_WARRIOR_N.png" alt="CODE_WARRIOR_N" border="0" style="width: 170px;height: 60px">            <!-- <img src="https://image.ibb.co/eaahPH/hackerearth.png" alt="hackerearth" border="0" /> -->
		</a>
			</div>
		<div id="head" class="col-sm-4 " style="padding-top: 28px">
			<strong>
				<h1 id="Code">Code Warrior</h1>
			</strong>
		</div>
		<div class="col-sm-6 ">
			<div id="clockdiv">
			    <div>
					<span id="days" class="days"></span>
					<div class="smalltext">days</div>
				</div>
				<div>
					<span id="hour" class="hours"></span>
					<div class="smalltext">Hours</div>
				</div>
				<div>
					<span id="minute" class="minutes"></span>
					<div class="smalltext">Minutes</div>
				</div>
				<div>
					<span id="second" class="seconds"></span>
					<div class="smalltext">Seconds</div>
				</div>
			</div>
			<script>
				// Set the date we're counting down to
				var countDownDate = new Date("May 9, 2019 9:59:59").getTime();

				// Update the count 	<h1>Countdown Clock</h1>down every 1 second
				var x = setInterval(function () {

					// Get todays date and time
					var now = new Date().getTime();

					// Find the distance between now an the count down date
					var distance = countDownDate - now;

					// Time calculations for days, hours, minutes and seconds
					var days = Math.floor(distance / (1000 * 60 * 60 * 24));
					var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
					var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
					var seconds = Math.floor((distance % (1000 * 60)) / 1000);

					// Output the result in an element with id="demo"
					document.getElementById("days").innerHTML = days;
					document.getElementById("hour").innerHTML = hours;
					document.getElementById("minute").innerHTML = minutes;
					document.getElementById("second").innerHTML = seconds;


					// If the count down is over, write some text
					if (distance < 0) {
						clearInterval(x);
						document.getElementById("days").innerHTML = "0";
						document.getElementById("hour").innerHTML = "0";
						document.getElementById("minute").innerHTML = "0";
						document.getElementById("second").innerHTML = "0";
					}
				}, 1000);
			</script>
		</div>

	</div>
</div>
<!-- <div class="row"> -->
<div class="jumbotron " style="padding-top: 15px;padding-left: 10px ;padding-bottom: 5px;margin-bottom:10px;margin-top:8px; ">
	<!-- <h5 style="padding-left: 0" >Problems</h5> -->
	<p>You have to solve as many problem(s) as you can before the timer ends and based on the accuracy of your submission you will
		get the scores.</p>
</div>
<!-- </div> -->

<!--<marquee width="40%" direction="left" height="30%" style="color:white;">-->
<!--    There was some bug in question no 4. You can submit again to test your code.-->
<!--</marquee>-->

<div class="row">
	<div class="col-12 my-3">

		<table class="table" id="ques">
			<thead>
				<tr>
					<th class="text-center">#</th>
					<th class="text-center">Question</th>
					<th class="text-center">Maximum Marks</th>
					<th class="text-center">Time Limit</th>
					<th class="text-center">Marks Obtained</th>
				</tr>
			</thead>
			<tbody>
				{% for object in object_list %}
				<tr>
					<td class="text-center">{{forloop.counter}}</td>
					<td id="question" class="text-center">
						<a style="color:#396" href="{{ object.get_absolute_url }}">{{ object }}</a>
					</td>
					<td class="text-center">
						<strong>100</strong>
					</td>
					<td class="text-center">
						<strong>1 second</strong>
					</td>
					<td class="text-center">
						<strong>{{object.marks_obtained}}</strong>
					</td>
				</tr>
				</ol>
				{% endfor %}
			</tbody>
		</table>


	</div>
</div>
<div style="margin-bottom: 20px">

</div>
{% endblock %}