accounts/passwords/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'
    ),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),
    url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    url(r'^password/reset/\
            (?P<uidb64>[0-9A-Za-z_\-]+)/\
            (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),
]

accounts/urls.py
from django.conf.urls import url

from .views import AccountEmailActivateView


app_name = 'account'


urlpatterns = [
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$',AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$',AccountEmailActivateView.as_view(), name='resend-activation')
]

judge/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.views.generic import RedirectView

from .views import home, contact_page
from accounts.views import RegisterView, ProfileView, LoginView, LeaderBoardView


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^leaderboard/$', LeaderBoardView.as_view(), name='leaderboard'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^questions/', include('questions.urls', namespace='question')),
    url(r'^question/', include('grader.urls', namespace='grader')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.conf.urls import url

from .views import QuestionListView, QuestionDetailView


app_name = 'question'


urlpatterns = [
    url(r'^$', QuestionListView.as_view(), name='list'),
    url(r'^(?P<code>[A-Z]+)/$', QuestionDetailView.as_view(), name='detail'),
]

accounts/forms.py
import re

from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.urls import reverse
from django.utils.safestring import mark_safe

from .models import EmailActivation

User = get_user_model()


class ReactivateEmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email)
        if not qs.exists():
            register_link = reverse('register')
            msg = """This email does not exist.
            Would you like to <a href="{link}">register</a>?""".format(link=register_link)
            raise forms.ValidationError(mark_safe(msg))
        return email


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'full_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('username', 'email', 'full_name', 'password', 'is_active', 'score', 'admin')

    def clean_password(self):
        return self.initial["password"]


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Username'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Password'}
    ))

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):  # This clean() method gets the entire form's data
        """
        With this function, the form itself handles the entire login process and only if the login
        is successful, it sends the data to the respective view.
        """
        request = self.request
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        response = {
            'success': False,
            'message': 'Login failed.'
        }


        user_qs = User.objects.filter(username=username, is_active=False)
        if user_qs.exists():
            # email is registered but not active
            email = user_qs.first().email
            link = reverse('account:resend-activation')
            reconfirm_msg = """Go to <a href="{resend_link}">resend confirmation email</a>.
            """.format(resend_link=link)
            is_email_confirmable = EmailActivation.objects.filter(email=email).confirmable().exists()
            email_activation_exists = EmailActivation.objects.email_exists(email).exists()
            if is_email_confirmable:
                msg1 = 'Please check your email to confirm your account or ' + reconfirm_msg.lower()
                response['message'] = msg1
                # raise forms.ValidationError(mark_safe(msg1))
            elif email_activation_exists:
                msg2 = 'Email not confirmed. ' + reconfirm_msg
                response['message'] = msg2
                # raise forms.ValidationError(mark_safe(msg2))
            else:
                response['message'] = 'This user is inactive.'
                # raise forms.ValidationError('This user is inactive.')
            return response

        user = authenticate(request, username=username, password=password)
        # If the is_active field is false, then the authenticate() method by default returns None
        if user is None:
            response['message'] = 'The username or the password is incorrect! Please try again.'
            # raise forms.ValidationError('Invalid credentials')
            return response

        login(request, user)
        response['success'] = True
        self.user = user
        return response


class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Username'}
    ))
    full_name = forms.CharField(label='Full Name', widget=forms.TextInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Full Name'}
    ))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Email'}
    ))


    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Password'}
    ))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control my-2', 'placeholder': 'Password'}
    ))

    class Meta:
        model = User
        fields = ('username', 'full_name', 'email')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if not re.match(r'^[a-zA-Z0-9]+$', username):
            raise forms.ValidationError('username can contain only alphabets and numbers')
        return username

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.http import Http404,HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user_model
from django.views.generic import ListView, DetailView, FormView, CreateView, View
from django.views.generic.edit import FormMixin
from django.utils.safestring import mark_safe
from django.urls import reverse

from .forms import LoginForm, RegisterForm, ReactivateEmailForm
from .models import EmailActivation
from judge.mixins import LoginRequiredMixin, AnonymousRequiredMixin, RequestFormAttachMixin, NextUrlMixin

User = get_user_model()


class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/profile.html'

    def get_object(self, *args, **kwargs):
        username = self.kwargs.get('username')
        instance = User.objects.filter(username=username).first()
        if instance is None:
            raise Http404('User not found')
        return instance


class LeaderBoardView(ListView):
    queryset = User.objects.filter(admin=False, is_active=True)
    template_name = 'accounts/leaderboard.html'


class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None

    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:  # Not confirmed but confirmable
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, 'Your email has been confirmed! Please login to continue.')
                return redirect('login')
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse('password_reset')
                    msg = """Your email has already been confirmed.
                    Do you want to <a href="{link}">reset you password</a>?""".format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect('login')
        context = {'form': self.get_form(), 'key': key}  # get_form() works because of the mixin
        return render(request, 'registration/activation_error.html', context)

    def post(self, request, *args, **kwargs):
        # create a form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = 'Activation link sent. Please check your email.'
        messages.success(self.request, msg)
        email = form.cleaned_data.get('email')
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        """
        This method had to be explicitly written because this view uses the basic django "View" class.
        If it had used some other view like ListView etc. Django would have handled it automatically.
        """
        context = {'form': form, 'key': self.key}
        return render(self.request, 'registration/activation_error.html', context)


class LoginView(AnonymousRequiredMixin, RequestFormAttachMixin, NextUrlMixin, FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = '/'
    default_url = '/'
    default_next = '/'

    def form_valid(self, form):
        request = self.request
        response = form.cleaned_data
        if not response.get('success'):
            messages.warning(request, mark_safe(response.get('message')))
            return redirect('login')
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(AnonymousRequiredMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'

    def form_valid(self, form):
        super(RegisterView, self).form_valid(form)
        messages.success(self.request, 'Verification link sent! Please check your email.')
        return redirect(self.success_url)

accounts/templates/accounts/leaderboard.html
{% extends 'base.html' %} {% block base_head %}
<title>LeaderBoard</title>
{% endblock %} {% block content %} {% if msg %}
<div class="alert alert-danger alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  {{ msg }}
</div>
{% endif %}

<div class="row">
  <div class="col-12 my-3">
      <h1 class="text-center" style="color:white">Leaderboard</h1>
  </div>
</div>
<div>
    <p style="color:white;">Q denotes Qualified.</p>
</div>
    <div class="col-12 my-3" style="background:white;margin-bottom:20px;">
	<table class="table table-striped" style="background:white;">
		<thead>
			<tr>
				<th class="text-center">Rank</th>
				<th class="text-center">Username</th>
				<th class="text-center">Score</th>
				<th class="text-center">Total Time (seconds)</th>
			</tr>
		</thead>
        <tbody>
          {% for object in object_list %}
            {% if not object.is_admin %}
              {% if object.username == username %}
              <tr>
                  {% if object.score >= 450 %}
                    <td class="text-center" ><p class="Qualified">Q {{ forloop.counter }}</p></td>
                    <td class="text-center">
                      <!--{{ object.username }}-->
                      {{ object.get_full_name }}
                      <!--<a href="{% url 'profile' object.username %}">{{ object.username }}</a>-->
                    </td>
                    <td class="text-center">{{ object.score }}</td>
                    <td class="text-center">{{ object.total_time }}</td>
                    {% else %}
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">
                      <!--{{ object.username }}-->
                      {{ object.get_full_name }}
                      <!--<a href="{% url 'profile' object.username %}">{{ object.username }}</a>-->
                    </td>
                    <td class="text-center">{{ object.score }}</td>
                    <td class="text-center">{{ object.total_time }}</td>
                    {% endif %}
              </tr>
              {% else %}
              <tr>
                {% if object.score >= 450 %}
                    <td class="text-center">Q {{ forloop.counter }}</td>
                    <td class="text-center">
                      <!--{{ object.username }}-->
                      {{ object.get_full_name }}
                      <!--<a href="{% url 'profile' object.username %}">{{ object.username }}</a>-->
                    </td>
                    <td class="text-center">{{ object.score }}</td>
                    <td class="text-center">{{ object.total_time }}</td>
                    {% else %}
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">
                      <!--{{ object.username }}-->
                      {{ object.get_full_name }}
                      <!--<a href="{% url 'profile' object.username %}">{{ object.username }}</a>-->
                    </td>
                    <td class="text-center">{{ object.score }}</td>
                    <td class="text-center">{{ object.total_time }}</td>
                    {% endif %}
              </tr>
              {% endif %}
             {% endif %}
          {% endfor %}
        </tbody>
	</table>
</div>
    {% if not object_list %}
    <div class="col-12 mb-4">
      Sign Up to display your name on the leaderboard.
    </div>
    {% endif %}
  <!--</div>-->
<!--</div>-->

<a style="margin-bottom: 20px" href="{% url 'question:list' %}">
  <button type="button" class="btn btn-success">Back To Problems</button>
</a>
<div style="margin-bottom: 20px"></div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block base_head %}
<title>Login</title>
{% endblock %}

{% block content %}

<div style="color: whitesmoke" class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<h1 style="color: whitesmoke" class="text-center">Login</h1>
	</div>
</div>
<hr/>
<div style="color: whitesmoke" class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<form method="POST"> {% csrf_token %}
		{{ form }}
		<div class="row">
			<div class="col my-1 mr-auto">
				<button type="submit" class="btn btn-primary">Sign In</button>
			</div>
			<div class="col my-3 ml-auto">
				<a href="{% url 'password_reset' %}" target="blank">Forgot Password?</a>
			</div>
		</div>
		</form>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block base_head %}
<title>Profile</title>
{% endblock %}

{% block content %}

<div class="jumbotron jumbotron-fluid" style="padding-top: 15px;padding-left: 10px ; margin-left: 17%;margin-right: 17%; padding-bottom: 5px;margin-bottom:10px;margin-top:8px; padding-right: 15px">
	<h1 style="align-self: auto;" class="text-center">{{ object.get_full_name }}</h1>
</div>

<div class="jumbotron" style="padding-top: 15px;padding-left: 10px ; margin-left: 17%;margin-right: 17%; padding-bottom: 5px;margin-bottom:10px;margin-top:8px; padding-right: 15px">
	<b>Username:</b> {{ object.username }}
	<p style="color: green">Score:{{ object.score }} </p>
	<a href="{% url 'question:list' %}">
		<button style="text-align: center" type="button" class="btn btn-success">Back To Problems</button>
	</a>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block base_head %}
<title>Register</title>
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<h1 style="color: whitesmoke" class="text-center">Register</h1>
	</div>
</div>
<div style="color: whitesmoke" class="row">
	<div class="col-12 col-md-4 mx-auto my-3">
		<form method="POST"> {% csrf_token %}
			{{ form }}
			<button type="submit" class="btn btn-primary">Sign Up</button>
		</form>
	</div>
</div>

{% endblock %}